### ISSUE TITLE
errors on Statement::column_* methods

### ISSUE THREAD

**Issue by goosetherumfoodle** [duckdb/duckdb-rs#204]
I'm on 0.8.1, using the bundled db. I can create tables and query rows, but all of the column methods fail.

Starting with the [basic example](https://github.com/duckdb/duckdb-rs/blob/main/examples/basic.rs), everything works, but if I stick the following at the end:

```
    let mut stmt = conn.prepare("SELECT id, name, data FROM person")?;
    let col_count = stmt.column_count();
    println!("COL COUNT: {}", col_count);
```

I get an error with the following backtrace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/duckdb-0.8.1/src/raw_statement.rs:70:21
```

I get the same for the other column_* methods.

**Comment by Mause** [comment]
Have you tried executing the query before retrieving the number of columns?

**Comment by goosetherumfoodle** [comment]
@Mause that does work, thanks! The documentation mentions needing to step first, but doesn't mention having to execute first...
