### ISSUE TITLE
[Question] how to convert UBIGINT[] to Vec<u64>

### ISSUE THREAD

**Issue by oliverdding** [duckdb/duckdb-rs#254]
I'm writting a little demo with a `UBIGINT[]` type column in my table.

While trying to query the table, the rustc told me that ```the trait bound `Vec<u64>: FromSql` is not satisfied```:

```rust
  let mut stmt = conn
        .prepare("SELECT * FROM users WHERE id = ?")
        .map_err(internal_error)?;

    stmt.query_row(params![id.0], |row| {
        Ok(Response::User(UserResponse {
            arr: row.get(1)?,
        }))
    })
    .map_err(|err| match err {
        duckdb::Error::QueryReturnedNoRows => (
            StatusCode::NOT_FOUND,
            ErrorResponse {
                code: -1,
                reason: "User not found".to_string(),
            },
        ),
        _ => internal_error(err),
    })
```

Here is UserResponse definition:

```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct UserResponse {
    pub arr: Vec<u64>,
}
```

Here is my table DDL:

```sql
    CREATE SEQUENCE IF NOT EXISTS seq_user_id START 0;
    
    CREATE TABLE IF NOT EXISTS users (
        id UBIGINT PRIMARY KEY DEFAULT nextval('seq_user_id'),
        arr UBIGINT[]
    );
```

---

After browsing the source code, I found that only `Vec<u8>` type are implementated with `FromSql` trait

<img width="861" alt="image" src="https://github.com/duckdb/duckdb-rs/assets/43624923/18e3675d-d6ee-476c-8ac1-4ed2087cfb0a">

Any advice are appreciated!

**Comment by dvic** [comment]
If I'm not mistaken, it's not yet implemented:

https://github.com/duckdb/duckdb-rs/blob/main/src/row.rs#L545-L580

**Comment by oliverdding** [comment]
Hi @dvic , thanks for your reference. I would close this issue and keep an eye on this.
