### ISSUE TITLE
Question: If an INSERT statement includes a RETURNING Clause, how can I retrieve the returned content?

### ISSUE THREAD

**Issue by paulomartins666** [duckdb/duckdb-rs#299]

**Comment by Mause** [comment]
Using the same methods you retrieve results from the database right now?

**Comment by paulomartins666** [comment]
the current insert method is to execute through the connection, and the returned result type is the number of rows changed, which seems to indicate the number of rows successfully written. What I mean is, how to get the value of the RETURNING field during insertion, such as the increasing row sequence number.

**Comment by Mause** [comment]
Like I said, the exact same way you get any other data:

```rust
let db = checked_memory_handle();
db.execute_batch("CREATE TABLE foo(x INTEGER);")?;

let stmt : i64 = db.query_row("INSERT INTO foo(x) VALUES (?) RETURNING x", [1], |r| r.get(0))?;

assert_eq!(stmt, 1);
```
