### ISSUE TITLE
Extension Metadata

### ISSUE THREAD

**Issue by 0xcaff** [duckdb/duckdb-rs#335]
Hey all, it seems like in version 0.10.2, some additional extension metadata requirements were added https://github.com/duckdb/duckdb/pull/11515 (its buried in the release notes as a non breaking change here https://github.com/duckdb/duckdb/releases/tag/v0.10.2). Prior to this release, the rust bindings using `duckdb_entrypoint` could be used to build extensions. Any plans to add something emitting extension metadata to `duckdb_entrypoint`? The metadata format is detailed in the linked PR. What's the recommended workflow for attaching this metadata?

**Comment by Mause** [comment]
Generally speaking the easiest way to add that metadata is to use the extension template - otherwise the format is straightforward enough to implement yourself

**Comment by 0xcaff** [comment]
Where is this extension template you speak of?

**Comment by Mause** [comment]
https://github.com/duckdb/extension-template

**Comment by Mause** [comment]
Otherwise something like this can be used: https://gist.github.com/Mause/888ad36325f462641a8e169f6183834a

**Comment by 0xcaff** [comment]
I was hoping for something integrated with the cargo toolchain, a workflow like https://github.com/overdrivenpotato/rust-psp/tree/master

I guess I'll build it myself and maybe upstream it if there's interest.
