### ISSUE TITLE
Extension Autoloading Error: Failed to Download JSON Extension

### ISSUE THREAD

**Issue by albertxos** [duckdb/duckdb-rs#351]
Description:

I'm encountering an issue with DuckDB while trying to execute a simple table creation command that involves JSON data. The specific error message indicates a failure to automatically install the required json extension due to a connection error. Below are the details:

Steps to Reproduce:

Execute the following command to create a table with a JSON column:

```rust
db_connection.execute(
    "CREATE TABLE IF NOT EXISTS credentials (id VARCHAR PRIMARY KEY, claims JSON)",
    params![],
)?;
```

The execution fails with the following error:

```
Failed to create table: Duckdb(DuckDBFailure(Error { code: Unknown, extended_code: 1 }, Some("Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'json':\nFailed to download extension \"json\" at URL \"http://extensions.duckdb.org/v0.10.2/linux_arm64/json.duckdb_extension.gz\"\nExtension \"json\" is an existing extension.\n (ERROR Connection)")))
Expected Behavior:
```

The command should execute successfully, creating the table with a JSON column without errors.

Actual Behavior:

The execution fails with an error indicating that the json extension cannot be downloaded due to a connection issue.

Additional Information:

- DuckDB version: 0.10.2
- Platform: Linux ARM64
- The application is running in a pod/container without internet connection

Would it be possible to include a mechanism to preload extensions or handle such scenarios where network issues prevent the automatic download of extensions? Any guidance or workaround to resolve this issue would be greatly appreciated.

**Comment by Mytherin** [comment]
Thanks for the report! As mentioned - this is expected behavior. (Auto-)installation of an extension requires an internet connection in order to download the extension. The extension can be downloaded and bundled with the image.

**Comment by albertxos** [comment]
Thank you

**Comment by albertxos** [comment]
> Thanks for the report! As mentioned - this is expected behavior. (Auto-)installation of an extension requires an internet connection in order to download the extension. The extension can be downloaded and bundled with the image.

I have tried to download and bundle into the image but somehow I don't know how to to it here is what I have done:
```Dockerfile
FROM alpine:3.20.2 AS build-env
ARG ARCH=aarch64
RUN apk add --no-cache wget gzip
WORKDIR /workspace

ARG TARGETARCH
RUN mkdir -p .duckdb/extensions/v1.0.0/linux_${TARGETARCH} && \
    wget -O .duckdb/extensions/v1.0.0/linux_${TARGETARCH}/json.duckdb_extension.gz \
    https://extensions.duckdb.org/v1.0.0/linux_${TARGETARCH}/json.duckdb_extension.gz && \
    gunzip .duckdb/extensions/v1.0.0/linux_${TARGETARCH}/json.duckdb_extension.gz


FROM gcr.io/distroless/cc-debian12
# Set the working directory
WORKDIR /workspace
# Copy the compiled binary to the image
# Copy the DuckDB extension directory from the build stage to the final image
ENV extension_directory="/workspace/.duckdb/extensions/"
WORKDIR /root
COPY --from=build-env ${extension_directory} ".duckdb/extensions/"

# Set the entry point for the container
ENTRYPOINT ["/workspace/ps-cli"]
```


But somehow my binary never finds the extensions:
```bash
called `Result::unwrap()` on an `Err` value: Duckdb(DuckDBFailure(Error { code: Unknown, extended_code: 1 }, Some("Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'json':\nFailed to download extension \"json\" at URL \"http://extensions.duckdb.org/v1.0.0/linux_arm64_gcc4/json.duckdb_extension.gz\"\nExtension \"json\" is an existing extension.\n")))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by albertxos** [comment]
maybe I should mention that I am using Rust client
